spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test_db?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    datasource: driver-class-name=org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000